# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/shaun/Programs/unreal/Linux_Unreal_Engine_5.7.4

TARGETS = \
	Side_Scroller_Test-Android-DebugGame  \
	Side_Scroller_Test-Android-Development  \
	Side_Scroller_Test-Android-Shipping  \
	Side_Scroller_Test-Linux-DebugGame  \
	Side_Scroller_Test-Linux-Development  \
	Side_Scroller_Test-Linux-Shipping  \
	Side_Scroller_Test-LinuxArm64-DebugGame  \
	Side_Scroller_Test-LinuxArm64-Development  \
	Side_Scroller_Test-LinuxArm64-Shipping  \
	Side_Scroller_Test \
	Side_Scroller_TestEditor-Linux-DebugGame  \
	Side_Scroller_TestEditor-Linux-Development  \
	Side_Scroller_TestEditor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend Side_Scroller_TestEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug Side_Scroller_TestEditor-Linux-Debug


Side_Scroller_Test-Android-DebugGame:
	 $(BUILD) Side_Scroller_Test Android DebugGame  -Project="/home/shaun/Documents/UnrealProjects/Side_Scroller_Test/Side_Scroller_Test.uproject" $(ARGS)

Side_Scroller_Test-Android-Development:
	 $(BUILD) Side_Scroller_Test Android Development  -Project="/home/shaun/Documents/UnrealProjects/Side_Scroller_Test/Side_Scroller_Test.uproject" $(ARGS)

Side_Scroller_Test-Android-Shipping:
	 $(BUILD) Side_Scroller_Test Android Shipping  -Project="/home/shaun/Documents/UnrealProjects/Side_Scroller_Test/Side_Scroller_Test.uproject" $(ARGS)

Side_Scroller_Test-Linux-DebugGame:
	 $(BUILD) Side_Scroller_Test Linux DebugGame  -Project="/home/shaun/Documents/UnrealProjects/Side_Scroller_Test/Side_Scroller_Test.uproject" $(ARGS)

Side_Scroller_Test-Linux-Development:
	 $(BUILD) Side_Scroller_Test Linux Development  -Project="/home/shaun/Documents/UnrealProjects/Side_Scroller_Test/Side_Scroller_Test.uproject" $(ARGS)

Side_Scroller_Test-Linux-Shipping:
	 $(BUILD) Side_Scroller_Test Linux Shipping  -Project="/home/shaun/Documents/UnrealProjects/Side_Scroller_Test/Side_Scroller_Test.uproject" $(ARGS)

Side_Scroller_Test-LinuxArm64-DebugGame:
	 $(BUILD) Side_Scroller_Test LinuxArm64 DebugGame  -Project="/home/shaun/Documents/UnrealProjects/Side_Scroller_Test/Side_Scroller_Test.uproject" $(ARGS)

Side_Scroller_Test-LinuxArm64-Development:
	 $(BUILD) Side_Scroller_Test LinuxArm64 Development  -Project="/home/shaun/Documents/UnrealProjects/Side_Scroller_Test/Side_Scroller_Test.uproject" $(ARGS)

Side_Scroller_Test-LinuxArm64-Shipping:
	 $(BUILD) Side_Scroller_Test LinuxArm64 Shipping  -Project="/home/shaun/Documents/UnrealProjects/Side_Scroller_Test/Side_Scroller_Test.uproject" $(ARGS)

Side_Scroller_Test: Side_Scroller_Test-Linux-Development

Side_Scroller_TestEditor-Linux-DebugGame:
	 $(BUILD) Side_Scroller_TestEditor Linux DebugGame  -Project="/home/shaun/Documents/UnrealProjects/Side_Scroller_Test/Side_Scroller_Test.uproject" $(ARGS)

Side_Scroller_TestEditor-Linux-Development:
	 $(BUILD) Side_Scroller_TestEditor Linux Development  -Project="/home/shaun/Documents/UnrealProjects/Side_Scroller_Test/Side_Scroller_Test.uproject" $(ARGS)

Side_Scroller_TestEditor: Side_Scroller_TestEditor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/shaun/Documents/UnrealProjects/Side_Scroller_Test/Side_Scroller_Test.uproject" -Game 

.PHONY: $(TARGETS)
